# Generated by Django 5.0.3 on 2024-03-28 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr_tickets', '0006_ticketorderheader_qr_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketorderheader',
            name='is_redeemed',
            field=models.BooleanField(default=False),
        ),
    ]
